sudo: false

notifications:
  email: false

language: swift
os: osx
osx_image: xcode10.2
xcode_workspace: gen/Listable/Listable.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod gen Listable.podspec

install:
  - echo

matrix:
  include:
    - xcode_scheme: Listable-Unit-Tests
