sudo: false

notifications:
  email: false

language: swift
os: osx
osx_image: xcode10.3
xcode_workspace: Demo/Demo.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

before_install:
  - gem update --system
  - gem install bundler
  - bundle install

install:
  - bundle exec pod repo update
  - bundle exec pod install

matrix:
  include:
    - xcode_scheme: Listable-CI-Test-Suite
